# Generated by Django 5.0 on 2024-12-06 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0084_alter_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date_only_choice',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
