# Generated by Django 5.0 on 2024-12-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0085_sale_date_only_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='number_caja',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
