# Generated by Django 5.0 on 2024-12-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0086_cashregister_number_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
